#dataSource:
#  driverClassName: com.mysql.jdbc.Driver
#  dbCreate: update
#  username: root
#  password: applelover
#
#environments:
#  development:
#    dataSource:
#      dbCreate: update
#      url: "jdbc:mysql://localhost:3306/ercmsfinals?serverTimezone=UTC"


#dataSource:
#  pooled: true
#  jmxExport: true
#  driverClassName: com.mysql.cj.jdbc.Driver
#  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  username: root
#  password: applelover
#environments:
#  development:
#    dataSource:
#      dbCreate: update
#      url: jdbc:mysql://localhost:3306/ercmsfinals?useUnicode=yes&characterEncoding=UTF-8
#
